### ISSUE TITLE
New layout

### ISSUE THREAD

**Issue by orlovnikita** [NoHomey/react-material-ui-keyboard#41]
Hello. Add please icon for changing layouts and make this action.

Thank you so much

**Comment by NoHomey** [comment]
There is already an icon/key for changing layouts `'Keyboard'`. It is described in [Creating Custom Keyboard Layout](https://github.com/NoHomey/react-material-ui-keyboard#creating-custom-keyboard-layout) section of the README. I've also added new example which uses two custom layouts which can be switched with the key between the `'Escape'` and `'CapsLock'` keys of each layout. The `'Keyboard'` moves in one layout from the `layouts` prop if the current layout is the last one it will switch back to the first.
