### ISSUE TITLE
Non selectable keys

### ISSUE THREAD

**Issue by orlovnikita** [NoHomey/react-material-ui-keyboard#42]
Make please non selectable key on keyboard if you cat

Thank you a lot :)

**Comment by NoHomey** [comment]
Ok, so you don't want custom styling but just disabled keys? Please be more specific do you want a keys without the hover effect but which are is still clickable or just a disabled keys?

**Comment by orlovnikita** [comment]
I want just disabling hover effect on keys while you move mouse on
keys or press keys by mouse

2016-11-09 18:12 GMT+02:00, Ivo Stratev notifications@github.com:

> Ok, so you don't want custom styling but just disabled keys? Please be more
> specific do you want a keys without the hover effect but which are is still
> clickable or just a disabled keys?
> 
> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/NoHomey/react-material-ui-keyboard/issues/42#issuecomment-259453303

## 

---

С уважением, Орлов Никита

**Comment by NoHomey** [comment]
New `disableEffects` `prop` has been added. When set to `true` it disables all ripples, focuses, hovers on all keys. I hope this is what you've requested @orlovnikita .
