### ISSUE TITLE
Could I custom this for "Khmer Keyboard" for smart phone?

### ISSUE THREAD

**Issue by thearabbit** [NoHomey/react-material-ui-keyboard#43]
I would like to create custom "Khmer Keyboard" for smart phone.
Could I use this? Please example and helping.

![image](https://cloud.githubusercontent.com/assets/4495160/23881354/a0631438-088c-11e7-90d0-8b4ba990aa9e.png)

**Comment by NoHomey** [comment]
Strings in JavaScript are utf-8 if the encoding supports it just create a custom layout and add it to the ```layouts``` prop.

**Comment by thearabbit** [comment]
thanks for your reply.
have any example?

**Comment by NoHomey** [comment]
Yes in `example` only it is in `TypeScript`: https://github.com/NoHomey/react-material-ui-keyboard/blob/master/example/custom_layouts/index.tsx
