### ISSUE TITLE
Options for cancelling the dialog

### ISSUE THREAD

**Issue by karldd** [NoHomey/react-material-ui-keyboard#44]
Firstly thanks for this great keyboard module!

Is it possible to add some additional options for closing the dialog? The escape key is not obvious to all users.
1. Option to cancel by clicking/touching anywhere outside the main dialog, i.e. trigger  `onRequestClose` when the user clicks/touches outside the dialog.
2. Option to add a [close icon](https://www.materialui.co/icon/close) in the top right.

Thanks!

**Comment by NoHomey** [comment]
Both can be added via extra props. I'll try to add them tomorrow.

**Comment by haunguyen90** [comment]
Hi @NoHomey any updates for this issue ?

**Comment by ghost** [comment]
Hey I'm looking for the very same functionality, can we get it soon @NoHomey ? :)

**Comment by NoHomey** [comment]
I'm busy until 1st of september ... but I'm accepting PRs.

**Comment by NoHomey** [comment]
Hello,

3 years have passed since I last updated the project.
Both React and Material-UI change a lot since then and the project needs to be rewritten to be usable nowadays.
I don't have time for the rewrite so I'll archive the project.

I'm sorry that I basically abaddoned the project ...
