### ISSUE TITLE
Customize theme

### ISSUE THREAD

**Issue by haunguyen90** [NoHomey/react-material-ui-keyboard#46]
Hi @NoHomey , Thank you very much for building this keyboard, I wanted to use your keyboard but the color is not good for my product, so is it possible to customize the theme of the keyboard?

**Comment by ghost** [comment]
I have exactly the same request :)

**Comment by ghost** [comment]
Found a way myself : 

```
import MuiThemeProvider from "material-ui/styles/MuiThemeProvider";
import getMuiTheme from "material-ui/styles/getMuiTheme";

const muiTheme = getMuiTheme({
  palette: {
    primary1Color: "#6884c2"
  }
});

```
Then wrap the component with this : 
```
 <MuiThemeProvider muiTheme={muiTheme}>
              <Keyboard ... />
            </MuiThemeProvider>
```
