### ISSUE TITLE
error TS2314 in KeyboardKey.d.ts

### ISSUE THREAD

**Issue by Kazooooo** [NoHomey/react-material-ui-keyboard#47]
ERROR in /***/***/node_modules/react-material-ui-keyboard/KeyboardKey.d.ts
(17,42): error TS2314: Generic type 'Component<P, S>' requires 2 type argument(s).

previous revision(6.2.0) has a  second argument but now it's gone.
could you add a 'any' or 'null' there?(not "void")

**Comment by qq942159888** [comment]
Uncaught TypeError: value.substring is not a function
    at Keyboard../node_modules/react-material-ui-keyboard/Keyboard.js.Keyboard.onKeyboard (Keyboard.js:133)

**Comment by NoHomey** [comment]
Hello,

3 years have passed since I last updated the project.
Both React and Material-UI change a lot since then and the project needs to be rewritten to be usable nowadays.
I don't have time for the rewrite so I'll archive the project.

I'm sorry that I basically abaddoned the project ...
