### ISSUE TITLE
Is this possible to put the keyboard out of the light box, and appear inside a Div? Thanks.

### ISSUE THREAD

**Issue by tedwong** [NoHomey/react-material-ui-keyboard#48]
as title, thanks.

**Comment by NoHomey** [comment]
Hello,

3 years have passed since I last updated the project.
Both React and Material-UI change a lot since then and the project needs to be rewritten to be usable nowadays.
I don't have time for the rewrite so I'll archive the project.

I'm sorry that I basically abaddoned the project ...
