### ISSUE TITLE
Update material ui version to 0.20 and React to 16 ?

### ISSUE THREAD

**Issue by jt3k** [NoHomey/react-material-ui-keyboard#49]
can u update material ui version to 0.20 and React to 16 ?

**Comment by pliuchkin** [comment]
I'd appreciate that too.

**Comment by NoHomey** [comment]
Hello,

3 years have passed since I last updated the project.
Both React and Material-UI change a lot since then and the project needs to be rewritten to be usable nowadays.
I don't have time for the rewrite so I'll archive the project.

I'm sorry that I basically abaddoned the project ...
