### ISSUE TITLE
Warning: Unknown event handler property `onTouchTap`. It will be ignored.

### ISSUE THREAD

**Issue by manavpandya** [NoHomey/react-material-ui-keyboard#50]
I have implemented the demo which is implemented into the readme

But I'm getting this error when my component loads 👍 

**Warning: Unknown event handler property `onTouchTap`. It will be ignored.**

And unable to close or type any digit from the keyboard, let me know the possibilities about that.

Thanks

**Comment by julesmoretti** [comment]
Likewise

**Comment by jpadilladev** [comment]
Having same problem

**Comment by NoHomey** [comment]
Hello,

3 years have passed since I last updated the project.
Both React and Material-UI change a lot since then and the project needs to be rewritten to be usable nowadays.
I don't have time for the rewrite so I'll archive the project.

I'm sorry that I basically abaddoned the project ...
