### ISSUE TITLE
Can't resolve 'material-ui/Dialog'

### ISSUE THREAD

**Issue by savnik** [NoHomey/react-material-ui-keyboard#53]
Issue: Can't resolve 'material-ui/Dialog'

It looks like the reference to material-ui/Dialog is invalid.
The solution is to import it via
`import Dialog from '@material-ui/core/Dialog';`
This may require to bump the material-ui version

Line: 
https://github.com/NoHomey/react-material-ui-keyboard/blob/9c3e9b9792666344606631409866d13efa198f55/src/Keyboard.tsx#L4

**Comment by NoHomey** [comment]
Hello,

3 years have passed since I last updated the project.
Both React and Material-UI change a lot since then and the project needs to be rewritten to be usable nowadays.
I don't have time for the rewrite so I'll archive the project.

I'm sorry that I basically abaddoned the project ...
